# This is a basic workflow to help you get started with Actions

name: build docs
on: 
  push:
    branches: 
      - master
  
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Install gfortran
        run: sudo apt install gfortran

