# This is a basic workflow to help you get started with Actions

name: build docs
on: 
  push:
    branches: 
      - master
  

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: deploy 
      env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: docs/_build/html
      run: | 
        cd $GITHUB_WORKSPACE
        git init 
        git config user.name "Github Actions"
        git config user.email "github-actions-bot@users.noreply.github.com"
        REPOSITORY_PATH="https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

        touch ${FOLDER}/.nojekyll

        git add -f $FOLDER
        git commit -m "Deploying to gh-pages from master" --quiet && \
        git push $REPOSITORY_PATH `git subtree split --prefix $FOLDER master`:gh-pages --force
